server:
  port: 8082

spring:
  application:
    name: user-service
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: noteforge-mvp-dev-jwt-secret-key-2026
  access-token-expiration: 900000
  refresh-token-expiration: 604800000

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.noteforge: DEBUG
    org.springframework.security: DEBUG
