global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'noteforge-note-service'
    static_configs:
      - targets: ['note-service:8081']
    metrics_path: '/actuator/prometheus'

  - job_name: 'noteforge-user-service'
    static_configs:
      - targets: ['user-service:8082']
    metrics_path: '/actuator/prometheus'
